import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/themes/mui/theme";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import CssBaseline from "@mui/material/CssBaseline";
import StoreProvider from "./StoreProvider";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        {/* Redux store provider */}
        <StoreProvider>
          {/* The AppRouterCacheProvider component is responsible for collecting the CSS generated by MUI System on the server and ensuring that the styles are appended to the <head> and not rendering in the <body> */}
          <AppRouterCacheProvider>
            {/* Applying MUI css baseline */}
            <CssBaseline />
            {/* MUI theme provider */}
            <ThemeProvider theme={theme}>{children}</ThemeProvider>
          </AppRouterCacheProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
