import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/themes/mui/theme";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import CssBaseline from "@mui/material/CssBaseline";
import StoreProvider from "./StoreProvider";
import Header from "@/components/complex/header";
import Footer from "@/components/footer";
import { Stack } from "@mui/material";
import Image from "next/image";
import background from "../../public/background.png";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Cromwell Profile Management App",
  description: "Technical assignment for Cromwell job application",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        {/* Redux store provider */}
        <StoreProvider>
          {/* The AppRouterCacheProvider component is responsible for collecting the CSS generated by MUI System on the server and ensuring that the styles are appended to the <head> and not rendering in the <body> */}
          <AppRouterCacheProvider>
            {/* Applying MUI css baseline */}
            <CssBaseline />
            {/* MUI theme provider */}
            <ThemeProvider theme={theme}>
              <Stack
                direction="column"
                sx={{
                  height: "100vh",
                  maxWidth: "100vw",
                  position: "relative",
                  minWidth: 370,
                }}
              >
                <Image
                  src={background}
                  alt="Background image"
                  priority
                  quality={50}
                  style={{
                    position: "absolute",
                    opacity: 0.03,
                    zIndex: -1,
                    width: "100%",
                    height: "100vh",
                    objectFit: "cover",
                  }}
                />
                <Header />
                {children}
                <Footer />
              </Stack>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
